# ***Tratando dados de itinerários***

Dados horários de intinerários, pede-se:

- Encontre e filtre as razões sociais que se repetem duas vezes;

- Encontre quais delas possuem intervalos em menos de uma hora.

https://dados.antt.gov.br/dataset/gerenciamento-de-autorizacoes

Uso do método .isin e da função pd.to_datetime

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('assets_dados/horarios.csv',sep = ';', engine='python', encoding="latin-1")
df

,cnpj,razao_social,data_autorizacao,prefixo,descricao_linha,tipo_veiculo,sentido,horario,segunda_feira,terca_feira,...,marco,abril,maio,junho,julho,agosto,setembro,outubro,novembro,dezembro
0,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,ida,14:00,x,x,...,x,x,x,x,x,x,x,x,x,x
1,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,08/07/2016,12-0140-00,BRASILIA(DF) - CALDAS NOVAS(GO),CONVEN. C/ SANITÁRIO,volta,07:00,x,x,...,x,x,x,x,x,x,x,x,x,x
2,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,06/11/2018,12-0140-61,BRASILIA(DF) - CALDAS NOVAS(GO),EXECUTIVO,ida,07:30,x,x,...,x,x,x,x,x,x,x,x,x,x
3,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,06/11/2018,12-0140-61,BRASILIA(DF) - CALDAS NOVAS(GO),EXECUTIVO,volta,14:00,x,x,...,x,x,x,x,x,x,x,x,x,x
4,04.192.453/0001-18,ALFA LUZ VIACAO TRANSPORTE LTDA,15/05/2017,12-0274-00,CALDAS NOVAS(GO) - ARAGUARI(MG),CONVEN. C/ SANITÁRIO,ida,06:45,NaN,NaN,...,x,x,x,x,x,x,x,x,x,x
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11472,18.538.045/0001-80,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,01/01/2016,13-0013-61,JOAO PESSOA(PB) - RECIFE(PE),EXECUTIVO,volta,11:00,x,x,...,x,x,x,x,x,x,x,x,x,x
11473,18.538.045/0001-80,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,01/01/2016,13-0013-61,JOAO PESSOA(PB) - RECIFE(PE),EXECUTIVO,volta,13:00,x,x,...,x,x,x,x,x,x,x,x,x,x
11474,18.538.045/0001-80,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,01/01/2016,13-0013-61,JOAO PESSOA(PB) - RECIFE(PE),EXECUTIVO,volta,14:00,x,x,...,x,x,x,x,x,x,x,x,x,x
11475,18.538.045/0001-80,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,01/01/2016,13-0013-61,JOAO PESSOA(PB) - RECIFE(PE),EXECUTIVO,volta,18:00,x,x,...,x,x,x,x,x,x,x,x,x,x
11476,18.538.045/0001-80,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,01/01/2016,13-0013-61,JOAO PESSOA(PB) - RECIFE(PE),EXECUTIVO,volta,19:00,x,x,...,x,x,x,x,x,x,x,x,x,x

In [8]:
df1 = df[['razao_social','horario']]
df1

                                            razao_social horario
0                        ALFA LUZ VIACAO TRANSPORTE LTDA   14:00
1                        ALFA LUZ VIACAO TRANSPORTE LTDA   07:00
2                        ALFA LUZ VIACAO TRANSPORTE LTDA   07:30
3                        ALFA LUZ VIACAO TRANSPORTE LTDA   14:00
4                        ALFA LUZ VIACAO TRANSPORTE LTDA   06:45
...                                                  ...     ...
11472  VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...   11:00
11473  VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...   13:00
11474  VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...   14:00
11475  VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...   18:00
11476  VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...   19:00

[11477 rows x 2 columns]

### Encontrando as que aparecem 2 vezes

In [12]:
filtro1 = df1['razao_social'].value_counts() == 2
filtro1

OSVALDO MENDES & CIA LTDA. - EMPRESA DOIS IRMÃOS    False
EMPRESA GONTIJO DE TRANSPORTES LTDA.                False
VIAÇÃO CAIÇARA LTDA.                                False
CONSÓRCIO GUANABARA DE TRANSPORTES                  False
AUTO VIAÇÃO CATARINENSE LTDA.                       False
                                                    ...
DANISTUR TRANSPORTE RODOVIARIO LTDA                  True
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA            True
EMPRESA TESTE SUPAS                                  True
TPC TRANSPORTES LTDA - ME                            True
VIAÇÃO PARANAIBA LTDA.                              False
Name: razao_social, Length: 208, dtype: bool

### Pegando apenas os valores "True"

In [13]:
filtro1[filtro1]

JS SERVIÇOS LOGISTICOS LTDA                                        True
TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.                    True
VIAÇÃO LUXOR LTDA - LLC TRANSPORTES                                True
VIACAO JLS LTDA                                                    True
ROTA DO SOL TRANSPORTE E TURISMO LTDA                              True
IRMÃOS NASCIMENTO TURISMO LTDA.                                    True
IVAIR CAETANO DO NASCIMENTO ? ME                                   True
VIAÇÃO TERESÓPOLIS E TURISMO LTDA.                                 True
EXPRESSO SANTA MARTA LTDA.                                         True
KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (CATEDRAL TURISMO)    True
EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.                    True
EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TURISMO LTDA - EPP     True
DANISTUR TRANSPORTE RODOVIARIO LTDA                                True
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA                          True
EMPRESA TESTE SUPAS                                                True
TPC TRANSPORTES LTDA - ME                                          True
Name: razao_social, dtype: bool

### Listas das razões sociais que aparecem 2 vezes

In [16]:
lista_filtrada = list(filtro1[filtro1].index)
lista_filtrada

['JS SERVIÇOS LOGISTICOS LTDA',
 'TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.',
 'VIAÇÃO LUXOR LTDA - LLC TRANSPORTES',
 'VIACAO JLS LTDA',
 'ROTA DO SOL TRANSPORTE E TURISMO LTDA',
 'IRMÃOS NASCIMENTO TURISMO LTDA.',
 'IVAIR CAETANO DO NASCIMENTO ? ME',
 'VIAÇÃO TERESÓPOLIS E TURISMO LTDA.',
 'EXPRESSO SANTA MARTA LTDA.',
 'KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (CATEDRAL TURISMO)',
 'EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.',
 'EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TURISMO LTDA - EPP',
 'DANISTUR TRANSPORTE RODOVIARIO LTDA',
 'VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA',
 'EMPRESA TESTE SUPAS',
 'TPC TRANSPORTES LTDA - ME']

In [17]:
len(lista_filtrada)

16

In [22]:
df1['razao_social'].isin(lista_filtrada)

0        False
1        False
2        False
3        False
4        False
         ...
11472    False
11473    False
11474    False
11475    False
11476    False
Name: razao_social, Length: 11477, dtype: bool

In [31]:
tabela_filtrada = df1[df1['razao_social'].isin(lista_filtrada)]
tabela_filtrada

,razao_social,horario,time
1792,DANISTUR TRANSPORTE RODOVIARIO LTDA,14:00,2022-02-26 14:00:00
1793,DANISTUR TRANSPORTE RODOVIARIO LTDA,09:30,2022-02-26 09:30:00
2934,EMPRESA TESTE SUPAS,13:00,2022-02-26 13:00:00
2935,EMPRESA TESTE SUPAS,14:00,2022-02-26 14:00:00
3189,EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TU...,10:30,2022-02-26 10:30:00
3190,EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TU...,17:30,2022-02-26 17:30:00
3809,EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.,17:15,2022-02-26 17:15:00
3810,EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.,07:00,2022-02-26 07:00:00
3850,EXPRESSO SANTA MARTA LTDA.,10:30,2022-02-26 10:30:00
3851,EXPRESSO SANTA MARTA LTDA.,15:30,2022-02-26 15:30:00
4515,IRMÃOS NASCIMENTO TURISMO LTDA.,07:00,2022-02-26 07:00:00
4516,IRMÃOS NASCIMENTO TURISMO LTDA.,07:00,2022-02-26 07:00:00
4517,IVAIR CAETANO DO NASCIMENTO ? ME,08:00,2022-02-26 08:00:00
4518,IVAIR CAETANO DO NASCIMENTO ? ME,09:00,2022-02-26 09:00:00
4877,JS SERVIÇOS LOGISTICOS LTDA,06:00,2022-02-26 06:00:00
4878,JS SERVIÇOS LOGISTICOS LTDA,06:00,2022-02-26 06:00:00
5008,KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (...,06:00,2022-02-26 06:00:00
5009,KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (...,12:00,2022-02-26 12:00:00
6934,ROTA DO SOL TRANSPORTE E TURISMO LTDA,00:00,2022-02-26 00:00:00
6935,ROTA DO SOL TRANSPORTE E TURISMO LTDA,00:00,2022-02-26 00:00:00
7494,TPC TRANSPORTES LTDA - ME,05:00,2022-02-26 05:00:00
7495,TPC TRANSPORTES LTDA - ME,04:30,2022-02-26 04:30:00
7641,TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.,08:30,2022-02-26 08:30:00
7642,TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.,08:15,2022-02-26 08:15:00
9866,VIACAO JLS LTDA,12:00,2022-02-26 12:00:00
9867,VIACAO JLS LTDA,12:00,2022-02-26 12:00:00
9868,VIAÇÃO LUXOR LTDA - LLC TRANSPORTES,22:30,2022-02-26 22:30:00
9869,VIAÇÃO LUXOR LTDA - LLC TRANSPORTES,22:30,2022-02-26 22:30:00
9870,VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA,04:50,2022-02-26 04:50:00
9871,VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA,10:00,2022-02-26 10:00:00
11277,VIAÇÃO TERESÓPOLIS E TURISMO LTDA.,07:00,2022-02-26 07:00:00
11278,VIAÇÃO TERESÓPOLIS E TURISMO LTDA.,17:00,2022-02-26 17:00:00

### Encontrando em quais horarios são menos de 1h

In [30]:
df1['time'] = pd.to_datetime(df['horario'])
df1

C:\Users\pedro\AppData\Local\Temp/ipykernel_13724/2557445064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['time'] = pd.to_datetime(df['horario'])

,razao_social,horario,time
0,ALFA LUZ VIACAO TRANSPORTE LTDA,14:00,2022-02-26 14:00:00
1,ALFA LUZ VIACAO TRANSPORTE LTDA,07:00,2022-02-26 07:00:00
2,ALFA LUZ VIACAO TRANSPORTE LTDA,07:30,2022-02-26 07:30:00
3,ALFA LUZ VIACAO TRANSPORTE LTDA,14:00,2022-02-26 14:00:00
4,ALFA LUZ VIACAO TRANSPORTE LTDA,06:45,2022-02-26 06:45:00
...,...,...,...
11472,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,11:00,2022-02-26 11:00:00
11473,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,13:00,2022-02-26 13:00:00
11474,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,14:00,2022-02-26 14:00:00
11475,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,18:00,2022-02-26 18:00:00
11476,VTR TRANSPORTE RODOVIARIO DE PASSAGEIROS LTDA ...,19:00,2022-02-26 19:00:00

In [33]:
print('Media dos Horarios')
pd.pivot_table(tabela_filtrada, index='razao_social',values='time')

Media dos Horarios

                                                                  time
razao_social
DANISTUR TRANSPORTE RODOVIARIO LTDA                2022-02-26 11:45:00
EMPRESA TESTE SUPAS                                2022-02-26 13:30:00
EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TUR... 2022-02-26 14:00:00
EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.    2022-02-26 12:07:30
EXPRESSO SANTA MARTA LTDA.                         2022-02-26 13:00:00
IRMÃOS NASCIMENTO TURISMO LTDA.                    2022-02-26 07:00:00
IVAIR CAETANO DO NASCIMENTO ? ME                   2022-02-26 08:30:00
JS SERVIÇOS LOGISTICOS LTDA                        2022-02-26 06:00:00
KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (C... 2022-02-26 09:00:00
ROTA DO SOL TRANSPORTE E TURISMO LTDA              2022-02-26 00:00:00
TPC TRANSPORTES LTDA - ME                          2022-02-26 04:45:00
TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.    2022-02-26 08:22:30
VIACAO JLS LTDA                                    2022-02-26 12:00:00
VIAÇÃO LUXOR LTDA - LLC TRANSPORTES                2022-02-26 22:30:00
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA          2022-02-26 07:25:00
VIAÇÃO TERESÓPOLIS E TURISMO LTDA.                 2022-02-26 12:00:00

In [40]:
serie_max = pd.pivot_table(tabela_filtrada, index='razao_social',values='time', aggfunc='max')
serie_max

                                                                  time
razao_social
DANISTUR TRANSPORTE RODOVIARIO LTDA                2022-02-26 14:00:00
EMPRESA TESTE SUPAS                                2022-02-26 14:00:00
EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TUR... 2022-02-26 17:30:00
EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.    2022-02-26 17:15:00
EXPRESSO SANTA MARTA LTDA.                         2022-02-26 15:30:00
IRMÃOS NASCIMENTO TURISMO LTDA.                    2022-02-26 07:00:00
IVAIR CAETANO DO NASCIMENTO ? ME                   2022-02-26 09:00:00
JS SERVIÇOS LOGISTICOS LTDA                        2022-02-26 06:00:00
KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (C... 2022-02-26 12:00:00
ROTA DO SOL TRANSPORTE E TURISMO LTDA              2022-02-26 00:00:00
TPC TRANSPORTES LTDA - ME                          2022-02-26 05:00:00
TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.    2022-02-26 08:30:00
VIACAO JLS LTDA                                    2022-02-26 12:00:00
VIAÇÃO LUXOR LTDA - LLC TRANSPORTES                2022-02-26 22:30:00
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA          2022-02-26 10:00:00
VIAÇÃO TERESÓPOLIS E TURISMO LTDA.                 2022-02-26 17:00:00

In [36]:
serie_min = pd.pivot_table(tabela_filtrada, index='razao_social',values='time', aggfunc='min')
serie_min

                                                                  time
razao_social
DANISTUR TRANSPORTE RODOVIARIO LTDA                2022-02-26 09:30:00
EMPRESA TESTE SUPAS                                2022-02-26 13:00:00
EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TUR... 2022-02-26 10:30:00
EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.    2022-02-26 07:00:00
EXPRESSO SANTA MARTA LTDA.                         2022-02-26 10:30:00
IRMÃOS NASCIMENTO TURISMO LTDA.                    2022-02-26 07:00:00
IVAIR CAETANO DO NASCIMENTO ? ME                   2022-02-26 08:00:00
JS SERVIÇOS LOGISTICOS LTDA                        2022-02-26 06:00:00
KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (C... 2022-02-26 06:00:00
ROTA DO SOL TRANSPORTE E TURISMO LTDA              2022-02-26 00:00:00
TPC TRANSPORTES LTDA - ME                          2022-02-26 04:30:00
TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.    2022-02-26 08:15:00
VIACAO JLS LTDA                                    2022-02-26 12:00:00
VIAÇÃO LUXOR LTDA - LLC TRANSPORTES                2022-02-26 22:30:00
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA          2022-02-26 04:50:00
VIAÇÃO TERESÓPOLIS E TURISMO LTDA.                 2022-02-26 07:00:00

In [41]:
serie_max - serie_min

                                                              time
razao_social
DANISTUR TRANSPORTE RODOVIARIO LTDA                0 days 04:30:00
EMPRESA TESTE SUPAS                                0 days 01:00:00
EXPRESSO BRASILEIRO TRANSPORTE RODOVIARIO E TUR... 0 days 07:00:00
EXPRESSO METRÓPOLIS TRANSPORTES E VIAGENS LTDA.    0 days 10:15:00
EXPRESSO SANTA MARTA LTDA.                         0 days 05:00:00
IRMÃOS NASCIMENTO TURISMO LTDA.                    0 days 00:00:00
IVAIR CAETANO DO NASCIMENTO ? ME                   0 days 01:00:00
JS SERVIÇOS LOGISTICOS LTDA                        0 days 00:00:00
KAWAGUCHI EVENTOS TRANSPORTE E TURISMO LTDA. (C... 0 days 06:00:00
ROTA DO SOL TRANSPORTE E TURISMO LTDA              0 days 00:00:00
TPC TRANSPORTES LTDA - ME                          0 days 00:30:00
TRANSPEN TRANSPORTE COLETIVO E ENCOMENDAS LTDA.    0 days 00:15:00
VIACAO JLS LTDA                                    0 days 00:00:00
VIAÇÃO LUXOR LTDA - LLC TRANSPORTES                0 days 00:00:00
VIAÇÃO MINEIROS TRANSPORTE E TURISMO LTDA          0 days 05:10:00
VIAÇÃO TERESÓPOLIS E TURISMO LTDA.                 0 days 10:00:00