## ***Desafio 2 - Dados do IBGE***

Importe a tabela dos 100 maiores municípios em relação ao PIB e responda as seguintes perguntas:

Quantos municípios estão no estado de São Paulo?
Qual a participação acumulada desses municípios?
Dicas e informações:

Fonte dos dados: https://www.ibge.gov.br/estatisticas/

In [1]:
import pandas as pd

In [23]:
file_path = 'assets_dados/PIB_100_maiores_cidades_2017.txt'
ibge_df = pd.read_csv(file_path, encoding="latin-1")
display(ibge_df)

,Municípios,Estado,Posição,PIB (1 000 R$),Participação (%),Participação acumulada (%)
0,São Paulo,SP,1º,6.992884e+08,10.622125,10.622125
1,Rio de Janeiro,RJ,2º,3.375945e+08,5.128028,15.750153
2,Brasília,DF,3º,2.446828e+08,3.716708,19.466861
3,Belo Horizonte,MG,4º,8.895117e+07,1.351160,20.818021
4,Curitiba,PR,5º,8.470236e+07,1.286621,22.104642
...,...,...,...,...,...,...
95,Três Lagoas,MS,96º,1.013170e+07,0.153900,54.717041
96,São José,SC,97º,1.013101e+07,0.153889,54.870930
97,Angra dos Reis,RJ,98º,1.009937e+07,0.153408,55.024338
98,Macapá,AP,99º,9.994877e+06,0.151821,55.176159
99,Cabo de Santo Agostinho,PE,100º,9.964401e+06,0.151358,55.327518

In [40]:
contador_estados = ibge_df['Estado'].value_counts()
contador_estados

SP    36
RJ    11
PR     8
MG     6
SC     5
PE     4
RS     4
BA     4
GO     3
ES     3
PA     2
MS     2
AL     1
RO     1
SE     1
PB     1
PI     1
MA     1
MT     1
RN     1
CE     1
AM     1
DF     1
AP     1
Name: Estado, dtype: int64

In [52]:
is_SP = ibge_df['Estado'] == 'SP'
is_SP #* Retorna uma series 

df_SP = ibge_df[is_SP] 
df_SP.head()

,Municípios,Estado,Posição,PIB (1 000 R$),Participação (%),Participação acumulada (%)
0,São Paulo,SP,1º,6.992884e+08,10.622125,10.622125
5,Osasco,SP,6º,7.791050e+07,1.183453,23.288095
10,Campinas,SP,11º,5.905356e+07,0.897018,28.307059
11,Guarulhos,SP,12º,5.574365e+07,0.846741,29.153800
14,Barueri,SP,15º,4.755359e+07,0.722335,31.408534

In [50]:
num_participacoes = df_SP['Participação acumulada (%)'].sum()
num_participacoes

1568.3383459619756